# Generated by Django 2.1.4 on 2018-12-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20181228_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
    ]
