# Generated by Django 2.1.4 on 2019-01-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20181228_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='notes',
            field=models.CharField(max_length=250),
        ),
    ]
